; PlatformIO Project Configuration File

[env:traffic-light-controller]
platform = espressif32@6.6.0
board = esp32-c6-devkitc-1
board_build.flash_size = 8MB
board_build.partitions = partitions_singleapp_large.csv
framework = espidf
monitor_speed = 115200
upload_speed = 115200
